---
# This workflow describes the publishing process,
# these actions will be triggered by a push event for all tags that will be added
name: Publish npm package
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'master'

jobs:
  # This job describes the process of building and testing the library using different versions of node js
  Build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      cacheBuild: true
    secrets: inherit

  # This job describes the process of publishing to the private Pluto registry
  Publish:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup node
        id: node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com
          scope: '@pluto-tv'
          cache: 'npm'

      - name: Use Cached Build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PKG_REPO_TOKEN }}
          NODE_OPTIONS: --experimental-worker
