name: release

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - 'fix/ARCH-4426'

jobs:
  publish:
    # if: |
    #   github.event.pull_request.merged == true &&
    #   github.base_ref == 'master' &&
    #   !contains(github.event.pull_request.labels.*.name, 'no-auto-release')
    # needs: release
    name: Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pluto-tv'
      - uses: actions/checkout@v3
      # - uses: ./.github/actions/setup-ssh
      #   with:
      #     key: ${{ secrets.PLUTO_DEPLOY_SSH_KEY }}
      - name: Publish NPM Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env
          npm install --silent
          npm publish
      - name: Check Publish Status
        if: ${{ failure() }}
        run: |
          echo "Error: Failed to publish Node client package."
          exit 1
